// <auto-generated />
namespace EFCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PK_FKStudent_Dept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PK_FKStudent_Dept));
        
        string IMigrationMetadata.Id
        {
            get { return "202302260754127_PK_FKStudent_Dept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
